### ISSUE TITLE
example of how to use Test.Falsify.Predicate.at?

### ISSUE THREAD

**Issue by mwotton** [well-typed/falsify#47]
I'd like to be able to use P.at to supply some more useful string context rather than the Show'ed form. I can't see how it's possible to make up the Expr argument needed to pass to it, though. Have I missed something?

I guess I can always newtype up something with a more pleasant Show instance, but it'd be nice to be able to do it in a more localised way.

**Comment by edsko** [comment]
I'm not fully sure I understand. We are talking about this function?

```haskell
at ::
     Predicate (x : xs)
  -> (Expr, String, x) -- ^ Renderded name, expression, and input proper
  -> Predicate xs
```

It doesn't require a `Show` instance, does it...? :thinking:

**Comment by mwotton** [comment]
it doesn't - i'm currently using P..$, which does require a Show instance. I'd like to use `at` instead so I don't need to, but how do I come up with a valid Expr from outside the module?

**Comment by edsko** [comment]
Oh, I see now! Yes, you are right, that's an omission. I went back and forth what I wanted to be part of the public API of `Predicate` and what not, and you're quite right, currently I've exposed too little and `at` is unusable. Apologies. Will try to fix asap.

**Comment by mwotton** [comment]
yep, works great. thanks!
