### ISSUE TITLE
Indexed Arbitrary typeclass

### ISSUE THREAD

**Issue by ejconlon** [well-typed/falsify#49]
Hello,

Great library so far, thanks for publishing it!

Even with integrated shrinking libraries, I find it useful to define my own project-local `Arbitrary` typeclass with Generics support to build `Gen` values for boring records. I understand that `Arbitrary` is problematic in general because for some types there isn't just one way to make a generator, but what about an _indexed_ variant, something like:

```
class Arbitrary p a where
  arbitrary :: Proxy p -> Gen a
```

This way projects can define their own local types for `p` and corresponding (non-orphan) instances as they see fit.

If it interests you, I would be happy to open a PR with the typeclass and Generic instances.

**Comment by edsko** [comment]
Yes, I think this could be useful. I agree that in principle having a default generator available for a given type, which you then can choose to  make use of or not, is a useful thing. I also agree that it would be nice to be able to derive such a default generator for things like records.

Let's emphasize this "optional default" aspect, something like

```haskell
class GenDefault tag a where 
  -- | Default generator for @a@
  --
  -- The type-level @tag@ allows to have multiple defaults. 
  genDefault :: Proxy p -> Gen a
```

One thing that isn't totally clear to me is what the instances in the library itself should look like. If we do

```haskell
instance GenDefault tag Bool where ..
```

(polymorphic in `tag`) then it becomes impossible for users to override their own defaults. If however we do

```haskell
data Falsify  -- used as type-level tag only

instance GenDefault Falsify Bool where ..
```

then users can take advantage of the defaults offered by the library, but if the moment that they don't, they'll need to define a bunch of instances, which is a bit annoying. 

Perhaps we could also have this in the library:

```haskell
newtype UsingDefaultGen tag a  = UsingDefaultGen a

instance GenDefault tag a => GenDefault tag' (UsingDefaultGen tag a) where
  genDefault _ = genDefault (Proxy @tag)
```

This would at least make it possible to selectively override a default somewhere, although it's still a bit cumbersome. Not sure if there isn't a better way.

One thing that I _would_ like to ensure is that the generic instance does _not_ apply/work for recursive types.

**Comment by ejconlon** [comment]
I think it would be a mistake to define default instances polymorphic in the tag because it would take away control from the user, so I much prefer the `UsingDefaultGen` solution with `DerivingVia`. (As an aside, I found that I could not convince GHC to coerce through Hedgehog's `Gen` type, but I can with Falsify's, so I am able to use `DerivingVia`.)

IMO it's ok to require a bunch of boilerplate `StandaloneDeriving` + `DerivingVia` instances like `deriving via (UsingDefaultGen Bool) instance GenDefault MyTag Bool`. It's no worse than defining `gen` functions, and the universe of types in a given domain is usually small. (No one is out there using every single newtype wrapper from `Data.Monoid`...)

I used this approach in a testing library for a binary serialization framework [here](https://github.com/ejconlon/dahdit-test/blob/4eded9b1c0f2fdaa54ff94d369f7c8cf729e2b5a/src/Test/Dahdit/Arb.hs). Personally, I found it more ergonomic to add another `Proxy` argument to select the argument type like

```
class Arb p a where
  arb :: Proxy p -> Proxy a -> Gen a
```

I also defined a number of newtype wrappers like `ArbSigned`, `ArbUnsigned`, `ArbEnum`, `ArbFractional`, and `ArbGeneric` that work how you would expect. I don't like my derivation of sequence generators; perhaps a newtype with `KnownNat` parameters for length bounds would be better.

**Comment by edsko** [comment]
* Agreed on the undesirability of the polymorphic version. 
* I'd prefer to omit the extra `Proxy` argument unless there is a convincing use case for it?
* The `ArbSigned` etc. newtypes are for deriving-via I guess?

I think we're on the same page here. Feel free to submit a PR :) Let's make this a new module though, so that is really is opt-in (`Test.Falsify.Generator.Default` I guess?).

**Comment by ejconlon** [comment]
I believe this is done with the two merged PRs. Just waiting on a 0.2.0 release :)

**Comment by edsko** [comment]
Hah, subtle hint? Will do :) (Is this technically speaking a major update..? :thinking: )

**Comment by ejconlon** [comment]
IMO it's fine to do a minor bump (looking at the changelog and going by my own experience upgrading to HEAD).
